# Generated by Django 3.1.2 on 2020-12-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoptrade_app', '0002_auto_20201218_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='end_date',
            new_name='end_date_support',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='start_date_support',
        ),
    ]
