# Generated by Django 3.1.2 on 2020-12-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoptrade_app', '0004_auto_20201218_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='Customer',
        ),
    ]
